@extends('public.layouts.product')
@section('title','OpsBridge - IT Operations and Workforce Control')
@section('description','Control IT assets, employees, software, endpoint devices, maintenance and compliance from one connected operational workspace.')
@section('scene-glow','#2ee4ff')
@section('product-class','product-opsbridge')
@section('login-url','https://opsbridge.niyantron.com/login')
@section('login-label','Sign in to OpsBridge')
@section('content')
<main>
<section class="hero"><div class="container hero-grid">
    <div class="hero-copy"><span class="kicker"><i class="bi bi-hdd-network"></i>Niyantron OpsBridge</span><h1>See every asset.<br>Understand every endpoint.<br><span class="gradient-text">Empower every team.</span></h1><p>OpsBridge connects IT assets, endpoint intelligence, employees, software governance, maintenance and compliance so teams can act from evidence instead of fragmented spreadsheets.</p><div class="actions"><a class="btn btn-primary" href="https://opsbridge.niyantron.com/login">Sign in to OpsBridge <i class="bi bi-box-arrow-in-right"></i></a><a class="btn btn-secondary" href="/contact">Request a guided demo</a></div></div>
    <div class="scene ops-scene" aria-hidden="true"><div class="ops-device"><div class="ops-screen"><div class="ops-device-head"><small>LIVE DEVICE GRAPH</small><span>● 1,248 CONNECTED</span></div><div class="ops-map"><i class="ops-link l1"></i><i class="ops-link l2"></i><i class="ops-link l3"></i><i class="ops-link l4"></i><div class="ops-hub"><i class="bi bi-pc-display"></i></div><span class="ops-spoke s1"><i class="bi bi-person-badge"></i> CUSTODIAN</span><span class="ops-spoke s2"><i class="bi bi-disc"></i> SOFTWARE</span><span class="ops-spoke s3"><i class="bi bi-shield-check"></i> COMPLIANCE</span><span class="ops-spoke s4"><i class="bi bi-tools"></i> SERVICE</span></div></div></div><div class="ops-float f1">DEVICE HEALTH<strong>96%</strong></div><div class="ops-float f2">LIFECYCLE<strong>TRACEABLE</strong></div></div>
    <div class="scene" aria-hidden="true"><div class="orbit o1"></div><div class="orbit o2"></div><i class="node n1"></i><i class="node n2"></i><i class="node n3"></i><div class="scene-core"><div class="command-head"><div><small>OPSBRIDGE CONTROL GRAPH</small><h3>Live operations</h3></div><span class="status">● Connected</span></div><div class="command-body"><div class="signal"><div class="signal-top"><span>Endpoint intelligence</span><span class="status">1,248 online</span></div><p>Discovery, hardware health, software evidence and remote actions.</p></div><div class="signal"><div class="signal-top"><span>Asset lifecycle</span><span class="status">Traceable</span></div><p>Procurement to assignment, repair, recovery and responsible disposal.</p></div><div class="signal"><div class="signal-top"><span>People operations</span><span class="status">In sync</span></div><p>Employee records, attendance, leave, payroll and self-service.</p></div></div></div></div>
</div></section>
<section class="product-tour"><div class="container"><div class="section-head"><div class="eyebrow">Guided product tour</div><h2>See how daily operations become one connected record.</h2><p>Select an operating stage to understand the user journey, live workspace and evidence created by OpsBridge.</p></div>
<input class="tour-input" type="radio" name="ops-tour" id="tour-1" checked><input class="tour-input" type="radio" name="ops-tour" id="tour-2"><input class="tour-input" type="radio" name="ops-tour" id="tour-3"><input class="tour-input" type="radio" name="ops-tour" id="tour-4"><input class="tour-input" type="radio" name="ops-tour" id="tour-5">
<div class="tour-shell"><nav class="tour-nav"><label for="tour-1"><i class="bi bi-box-seam"></i><span><strong>Asset lifecycle</strong><small>Acquire to dispose</small></span></label><label for="tour-2"><i class="bi bi-cpu"></i><span><strong>Endpoint control</strong><small>Discover and act</small></span></label><label for="tour-3"><i class="bi bi-disc"></i><span><strong>Software</strong><small>Entitlement and risk</small></span></label><label for="tour-4"><i class="bi bi-people"></i><span><strong>People operations</strong><small>Employee workspace</small></span></label><label for="tour-5"><i class="bi bi-tools"></i><span><strong>Service and insight</strong><small>Maintain and report</small></span></label></nav>
<div class="tour-stage">
@foreach([
['ASSET LIFECYCLE','Control every asset from acquisition to exit','Traceable','bi-cart-check','Acquire and receive','Supplier, cost, warranty and ownership','bi-person-badge','Assign and recover','Employee custody and acknowledgements','bi-recycle','Transfer or dispose','Sanitization, resale and evidence','A single asset record connects commercial history, ownership, custody, location, repair and disposal evidence.',['Purchase and receiving lineage','Barcode, serial and custodian history','Approved transfer and disposal controls'],'Endpoint control → connect the physical device to live telemetry'],
['ENDPOINT INTELLIGENCE','Turn enrolled devices into live operational evidence','Connected','bi-pc-display','Device discovery','Hardware, OS and configuration facts','bi-activity','Health and alerts','Storage, security and operational signals','bi-terminal','Controlled actions','Approved commands with execution history','Windows, Linux and macOS agents keep device records current and give authorized teams safe operational actions.',['Automated hardware inventory','Health and compliance exceptions','Audited remote action history'],'Software → reconcile discovered installations with entitlement'],
['SOFTWARE GOVERNANCE','Know what is installed, licensed and at risk','Compliant','bi-search','Discover software','Normalized publisher and product evidence','bi-key','Manage entitlement','Licences, contracts and assignments','bi-shield-exclamation','Resolve exposure','Overuse, prohibited apps and exceptions','Connect discovery to software licences, assignments, requests and policy so audits are based on evidence—not spreadsheets.',['Installation-to-entitlement reconciliation','Software request and approval workflow','Compliance position and remediation'],'People operations → connect users, roles and device custody'],
['HRMS AND SELF-SERVICE','Connect employees with the operations around them','In sync','bi-person-vcard','Employee record','Profile, documents and organization context','bi-calendar-check','Time and leave','Attendance, shifts and approvals','bi-cash-stack','Payroll and service','Salary structure and employee access','Employee identity connects HR workflows with assigned assets, software access and organizational responsibility.',['Employee files and document controls','Attendance, leave and shifts','Payroll and employee self-service'],'Service → maintain assets and manage operational exceptions'],
['MAINTENANCE AND ANALYTICS','Move from reactive follow-up to managed operations','Actionable','bi-wrench-adjustable','Service lifecycle','Breakdown, repair and return-to-service','bi-calendar2-check','AMC and schedule','Contracts and preventive maintenance','bi-speedometer2','Executive insight','Exposure, exceptions and performance','Maintenance, contracts, security history and executive reporting stay connected to the same assets, endpoints and owners.',['Preventive and breakdown maintenance','Vendor, warranty and AMC control','Executive dashboards and audit reports'],'Decision → prioritize risk, cost, SLA and lifecycle action']
] as $tour)<article class="tour-panel"><div class="tour-panel-head"><div><small>{{ $tour[0] }}</small><h3>{{ $tour[1] }}</h3></div><span class="tour-state">{{ $tour[2] }}</span></div><div class="tour-body"><div class="demo-window"><div class="demo-toolbar"><span>OPSBRIDGE · LIVE OPERATIONS</span><span class="demo-dots"><i></i><i></i><i></i></span></div><div class="demo-content">@foreach([[3,4,5],[6,7,8],[9,10,11]] as $row)<div class="demo-row"><i class="bi {{ $tour[$row[0]] }}"></i><div><strong>{{ $tour[$row[1]] }}</strong><small>{{ $tour[$row[2]] }}</small></div><em>ACTIVE</em></div>@endforeach</div></div><div class="tour-story"><h4>What the user achieves</h4><p>{{ $tour[12] }}</p><ul>@foreach($tour[13] as $point)<li><i class="bi bi-check-circle-fill"></i>{{ $point }}</li>@endforeach</ul><div class="next-module"><strong>Next:</strong> {{ $tour[14] }}</div></div></div></article>@endforeach
</div></div></div></section>
<section class="section alt"><div class="container"><div class="section-head"><div class="eyebrow">Connected capabilities</div><h2>One platform for the moving parts of daily operations.</h2><p>Each module works independently, while shared identity, permissions, audit history and reporting keep the organization connected.</p></div><div class="feature-grid">
@foreach([
['bi-box-seam','IT Asset Management','Track acquisition, ownership, assignment, location, custody, warranty, repair and disposal for every asset.'],
['bi-cpu','Endpoint Agent','Enroll Windows, Linux and macOS devices for automated inventory, discovery, health signals and controlled commands.'],
['bi-disc','Software Governance','Reconcile installations with entitlements, control requests, detect compliance gaps and produce audit evidence.'],
['bi-people','HRMS','Manage employee profiles, documents, attendance, leave, shifts, payroll and employee self-service.'],
['bi-tools','Maintenance and AMC','Plan preventive maintenance, manage breakdowns, vendors, service contracts, repairs and return-to-service.'],
['bi-shield-check','Security and Audit','Role-based access, tenant separation, immutable activity history and management-ready compliance reporting.'],
['bi-cart-check','Procurement','Control suppliers, purchase requests, approvals, purchase orders and receiving without losing asset lineage.'],
['bi-recycle','Lifecycle and Disposal','Recover assets, approve transfers, sanitize devices and maintain evidence through resale or disposal.'],
['bi-graph-up-arrow','Executive Analytics','See asset exposure, software risk, workforce status, service performance and operational exceptions.']
] as $i=>$feature)<article class="feature"><span class="number">{{ str_pad($i+1,2,'0',STR_PAD_LEFT) }}</span><div class="icon"><i class="bi {{ $feature[0] }}"></i></div><h3>{{ $feature[1] }}</h3><p>{{ $feature[2] }}</p></article>@endforeach
</div></div></section>
<section class="section"><div class="container"><div class="section-head"><div class="eyebrow">From request to evidence</div><h2>Workflows people can follow without chasing context.</h2><p>OpsBridge guides each role toward the next action while preserving approval boundaries and a complete operational record.</p></div><div class="flow"><div class="flow-step"><span>1</span><h3>Request</h3><p>An employee or team raises a structured requirement.</p></div><div class="flow-step"><span>2</span><h3>Review</h3><p>Approvers see policy, availability, cost and risk context.</p></div><div class="flow-step"><span>3</span><h3>Execute</h3><p>Teams assign, procure, repair, recover or remediate.</p></div><div class="flow-step"><span>4</span><h3>Prove</h3><p>Every decision becomes searchable evidence and reporting.</p></div></div><div class="outcomes"><div class="outcome"><strong>One record</strong><p>Hardware, software, people and service history stay connected instead of living in separate files.</p></div><div class="outcome"><strong>Clear ownership</strong><p>Every request, asset and exception has a custodian, responsible team and visible next action.</p></div></div></div></section>
<div class="container cta"><div><div class="eyebrow">See your operations clearly</div><h2>Bring control to assets, endpoints and people.</h2><p>Start with the modules you need and expand without rebuilding your operational foundation.</p></div><div class="actions"><a class="btn btn-primary" href="/contact">Request OpsBridge demo</a><a class="btn btn-secondary" href="https://opsbridge.niyantron.com/login">Customer login</a></div></div>
</main>
@endsection
