<style>
    .nya-launcher{position:fixed;right:24px;bottom:24px;z-index:120;display:flex;align-items:center;gap:11px;padding:11px 16px 11px 11px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:linear-gradient(135deg,#176dff,#6c4cff);color:#fff;box-shadow:0 20px 55px rgba(24,89,255,.36);font:800 13px Inter,system-ui;cursor:pointer;transition:.22s}.nya-launcher:hover{transform:translateY(-3px);box-shadow:0 25px 65px rgba(24,89,255,.46)}.nya-launcher-icon{position:relative;width:38px;height:38px;display:grid;place-items:center;border-radius:13px;background:rgba(255,255,255,.16);font-size:18px}.nya-live{position:absolute;right:-1px;top:-1px;width:9px;height:9px;border:2px solid #4770ff;border-radius:50%;background:#24e3a4}.nya-launcher small{display:block;margin-top:2px;color:rgba(255,255,255,.7);font-size:9px;font-weight:600}
    .nya-chat{position:fixed;right:24px;bottom:88px;z-index:121;width:min(400px,calc(100vw - 28px));height:min(650px,calc(100vh - 112px));display:none;grid-template-rows:auto 1fr auto;border:1px solid rgba(255,255,255,.15);border-radius:26px;overflow:hidden;background:#f8fbff;color:#0b1f3a;box-shadow:0 32px 100px rgba(2,13,32,.45);font-family:Inter,system-ui}.nya-chat.open{display:grid;animation:nya-in .22s ease-out}@keyframes nya-in{from{opacity:0;transform:translateY(16px) scale(.97)}}
    .nya-head{padding:17px 18px;color:#fff;background:radial-gradient(circle at 85% 0,rgba(69,232,255,.2),transparent 32%),linear-gradient(135deg,#071b37,#123f79)}.nya-head-row{display:flex;align-items:center;justify-content:space-between;gap:12px}.nya-identity{display:flex;align-items:center;gap:11px}.nya-avatar{width:42px;height:42px;display:grid;place-items:center;border:1px solid rgba(255,255,255,.16);border-radius:14px;background:linear-gradient(135deg,#2878ff,#7457ff);font-size:19px}.nya-identity strong{display:block;font-size:14px}.nya-identity small{display:flex;align-items:center;gap:5px;margin-top:3px;color:#a9c5e8;font-size:10px}.nya-identity small i{width:6px;height:6px;border-radius:50%;background:#2ee6a6}.nya-close{width:34px;height:34px;border:0;border-radius:10px;background:rgba(255,255,255,.08);color:#fff;cursor:pointer}.nya-context{margin-top:13px;padding:9px 11px;border:1px solid rgba(255,255,255,.1);border-radius:11px;color:#bcd0e9;background:rgba(255,255,255,.05);font-size:10px;line-height:1.45}
    .nya-messages{overflow:auto;padding:18px;background:linear-gradient(180deg,#f5f9ff,#fff)}.nya-message{display:flex;gap:8px;margin-bottom:13px}.nya-message.user{justify-content:flex-end}.nya-bubble{max-width:86%;padding:11px 13px;border-radius:16px 16px 16px 5px;background:#eaf1fb;color:#18334f;font-size:12px;line-height:1.55;box-shadow:0 4px 14px rgba(9,36,72,.05)}.nya-message.user .nya-bubble{border-radius:16px 16px 5px 16px;background:linear-gradient(135deg,#216fff,#604cff);color:#fff}.nya-bubble strong{color:#092f67}.nya-message.user strong{color:#fff}.nya-links{display:flex;flex-wrap:wrap;gap:7px;margin-top:10px}.nya-links a{padding:7px 10px;border:1px solid #cbdcf2;border-radius:999px;color:#1454a0;text-decoration:none;font-size:10px;font-weight:800;background:#fff}.nya-thinking span{display:inline-block;width:5px;height:5px;margin:0 2px;border-radius:50%;background:#7390b4;animation:nya-dot 1s infinite}.nya-thinking span:nth-child(2){animation-delay:.15s}.nya-thinking span:nth-child(3){animation-delay:.3s}@keyframes nya-dot{50%{transform:translateY(-4px);opacity:.5}}
    .nya-compose{padding:12px;border-top:1px solid #dce7f3;background:#fff}.nya-chips{display:flex;gap:7px;overflow-x:auto;padding-bottom:10px;scrollbar-width:none}.nya-chip{flex:0 0 auto;border:1px solid #cdddf0;border-radius:999px;padding:8px 10px;background:#f8fbff;color:#20476f;font-size:10px;font-weight:750;cursor:pointer}.nya-form{display:grid;grid-template-columns:1fr 42px;gap:8px}.nya-input{min-width:0;border:1px solid #cbd9e9;border-radius:14px;padding:12px 13px;outline:0;color:#102944;background:#f8fbff;font:12px Inter,system-ui}.nya-input:focus{border-color:#4a83ff;box-shadow:0 0 0 3px rgba(74,131,255,.1)}.nya-send{border:0;border-radius:13px;color:#fff;background:linear-gradient(135deg,#2878ff,#7457ff);cursor:pointer;font-size:16px}.nya-note{text-align:center;margin-top:8px;color:#8aa0b8;font-size:8px}
    @media(max-width:620px){.nya-launcher{right:14px;bottom:14px}.nya-launcher-copy{display:none}.nya-launcher{padding:9px}.nya-chat{right:7px;bottom:7px;width:calc(100vw - 14px);height:calc(100vh - 14px);border-radius:22px}.nya-bubble{max-width:91%}}
</style>
<button class="nya-launcher" id="nyaLauncher" type="button" aria-label="Chat with Niyantron Product Advisor"><span class="nya-launcher-icon"><i class="bi bi-stars"></i><i class="nya-live"></i></span><span class="nya-launcher-copy">Ask Niyantron<small>Product advisor · Online</small></span></button>
<section class="nya-chat" id="nyaChat" aria-label="Niyantron Product Advisor" aria-hidden="true">
    <header class="nya-head"><div class="nya-head-row"><div class="nya-identity"><span class="nya-avatar"><i class="bi bi-stars"></i></span><div><strong>Niyantron Product Advisor</strong><small><i></i>Ready to help</small></div></div><button class="nya-close" id="nyaClose" type="button" aria-label="Close chat"><i class="bi bi-x-lg"></i></button></div><div class="nya-context" id="nyaContext">I can explain products, compare modules and help you choose the right next step.</div></header>
    <div class="nya-messages" id="nyaMessages" aria-live="polite"></div>
    <footer class="nya-compose"><div class="nya-chips" id="nyaChips"><button class="nya-chip" data-question="Which product is right for me?">Help me choose</button><button class="nya-chip" data-question="Explain Niyantron ERP">Explore ERP</button><button class="nya-chip" data-question="Explain OpsBridge">Explore OpsBridge</button><button class="nya-chip" data-question="Compare ERP and OpsBridge">Compare products</button><button class="nya-chip" data-question="I want to book a demo">Book demo</button></div><form class="nya-form" id="nyaForm"><input class="nya-input" id="nyaInput" autocomplete="off" maxlength="500" placeholder="Ask in English, Hindi or Hinglish…" aria-label="Your question"><button class="nya-send" type="submit" aria-label="Send"><i class="bi bi-arrow-up"></i></button></form><div class="nya-note">Product guidance only · Never share passwords or confidential business data</div></footer>
</section>
<script>
(()=>{const launcher=document.getElementById('nyaLauncher'),chat=document.getElementById('nyaChat'),close=document.getElementById('nyaClose'),messages=document.getElementById('nyaMessages'),form=document.getElementById('nyaForm'),input=document.getElementById('nyaInput'),chips=document.getElementById('nyaChips'),context=document.getElementById('nyaContext');if(!launcher||!chat)return;
const page=location.pathname.includes('/products/erp')?'erp':location.pathname.includes('/products/opsbridge')?'opsbridge':'home';const links={erp:'<div class="nya-links"><a href="/products/erp">Explore ERP</a><a href="https://erp.niyantron.com/login">ERP sign in</a><a href="/contact">Request demo</a></div>',ops:'<div class="nya-links"><a href="/products/opsbridge">Explore OpsBridge</a><a href="https://opsbridge.niyantron.com/login">OpsBridge sign in</a><a href="/contact">Request demo</a></div>',demo:'<div class="nya-links"><a href="/contact">Request a guided demo</a></div>',offers:'<div class="nya-links"><a href="https://bid.niyantron.com">Open Niyantron Offers</a></div>'};
let history=[];try{history=JSON.parse(sessionStorage.getItem('niyantron-advisor-history')||'[]').slice(-16)}catch(e){}const add=(html,who='bot',persist=true)=>{const row=document.createElement('div');row.className='nya-message '+who;row.innerHTML='<div class="nya-bubble">'+html+'</div>';messages.appendChild(row);messages.scrollTop=messages.scrollHeight;if(persist){history.push({html,who});history=history.slice(-16);try{sessionStorage.setItem('niyantron-advisor-history',JSON.stringify(history))}catch(e){}}};
const welcome=()=>{if(page==='erp'){context.textContent='You are exploring Niyantron ERP · Ask about any module or workflow.';add('Namaste! Aap <strong>Niyantron ERP</strong> explore kar rahe hain. Main procurement, QC, inventory, CRM, sales, finance, reports aur Offers ke baare mein explain kar sakta hoon. Aap kya samajhna chahenge?')}else if(page==='opsbridge'){context.textContent='You are exploring OpsBridge · Ask about assets, endpoints, people or software.';add('Hello! Aap <strong>OpsBridge</strong> experience mein hain. Main IT assets, endpoint agent, software compliance, HRMS, maintenance aur lifecycle workflows explain kar sakta hoon.')}else add('Namaste! Main <strong>Niyantron Product Advisor</strong> hoon. Aap apni business requirement simple language mein batayein—main suitable product, modules aur next step suggest karunga.')};
const answer=q=>{const s=q.toLowerCase();if(/hello|hi |hey|namaste|namaskar|jai shri ram/.test(s))return 'Namaste! Main yahin hoon. Aap apni requirement ya kisi product/module ka naam batayein.';
if(/compare|difference|antar|dono/.test(s))return '<strong>OpsBridge</strong> assets, endpoints, employees, software and IT lifecycle ko control karta hai. <strong>Niyantron ERP</strong> sourcing, procurement, category-specific QC, inventory, CRM, sales and finance chalata hai. Organization dono products independently ya together use kar sakti hai.'+links.erp+links.ops;
if(/which product|right for me|suggest|choose|kaunsa|konsa|recommend/.test(s))return 'Agar challenge <strong>IT assets, devices, employees, software licences or maintenance</strong> hai, OpsBridge suitable hai. Agar challenge <strong>purchase, QC, stock, sales, CRM or accounts</strong> hai, ERP suitable hai. Dono areas connected chahiye to organization both products use kar sakti hai. Aapka main challenge kya hai?';
if(/erp|purchase|procure|quality|\bqc\b|inventory|stock|barcode|supplier|sales|finance|ledger|gst|crm/.test(s)){let detail='Niyantron ERP procurement se sale aur accounting tak guided workflow deta hai. Isme multi-company structure, catalogue masters, flexible purchase routes, dynamic category-wise QC, unit IDs/barcodes, inventory, CRM, sales, supplier/customer ledgers, GST, reports and CEO dashboard शामिल हैं.';if(/qc|quality/.test(s))detail='ERP ka <strong>Dynamic Quality Studio</strong> har category ke liye different form, parameters, conditions, defect groups, evidence, grading and readiness rules define karta hai. QC supplier site, warehouse ya optional route par ho sakta hai.';else if(/barcode|serial|imei|inventory/.test(s))detail='Approved serialized unit ko internal unique Stock Unit ID aur category-specific barcode मिलता है. Serial number/IMEI external identifiers रहते हैं; ownership, location and movement company-specific traceable रहते हैं.';else if(/purchase|procure|supplier/.test(s))detail='Purchase direct, approved request, identified-unit, known-product bulk ya supplier-site selection route se हो सकती है. Solo user ke liye unnecessary approvals optional रहते हैं; teams controlled approvals use कर सकती हैं.';return detail+links.erp}
if(/opsbridge|asset|endpoint|device|software|license|licence|employee|hrms|attendance|payroll|maintenance|amc|disposal/.test(s)){let detail='<strong>OpsBridge</strong> IT assets, endpoint telemetry, employees, software governance, procurement, maintenance, AMC and disposal ko one evidence chain mein जोड़ता है.';if(/endpoint|device|agent/.test(s))detail='OpsBridge endpoint agent Windows, Linux and macOS devices se hardware, OS, software and health evidence collect karta hai aur authorized audited actions enable karta hai.';else if(/software|license|licence/.test(s))detail='Software Governance discovered installations ko licences and entitlements se reconcile karta hai, compliance gaps दिखाता है aur request/approval/remediation evidence रखता है.';else if(/employee|hrms|attendance|payroll/.test(s))detail='OpsBridge HRMS employee profiles, documents, attendance, shifts, leave, payroll and self-service ko assigned assets and organizational responsibility se connect karta hai.';return detail+links.ops}
if(/offer|bid|broadcast|auction|buyer|negot/.test(s))return '<strong>Niyantron Offers</strong> connected buyers ke liye private B2B offer and bidding portal hai. Organization available stock ya controlled supplier opportunity broadcast kar सकती है; buyer bid, counteroffer and allocation progress securely देखता है.'+links.offers;
if(/price|pricing|cost|kitna|charges|plan/.test(s))return 'Pricing organization size, selected products, users, endpoints and required modules par depend करेगी. सही proposal ke liye short discovery call best रहेगा.'+links.demo;
if(/demo|contact|call|talk|sales team/.test(s))return 'Bilkul. Guided demo mein hum aapke actual operating model ke अनुसार relevant workflow दिखाएंगे—generic slideshow नहीं.'+links.demo;
if(/login|sign in|open account/.test(s))return 'Existing customer सही product login use कर सकता है. Super Admin platform login customer operations ke लिए नहीं है.'+links.erp+links.ops;
return 'Main is question ko confidently map nahi kar पाया. Aap thoda context दें—ye <strong>IT assets/people</strong> se related hai ya <strong>purchase/QC/inventory/sales</strong> se? Main सही workflow suggest करूंगा. '+links.demo};
const send=q=>{q=q.trim();if(!q)return;add(q.replace(/[<>]/g,''),'user');input.value='';const wait=document.createElement('div');wait.className='nya-message';wait.innerHTML='<div class="nya-bubble nya-thinking"><span></span><span></span><span></span></div>';messages.appendChild(wait);messages.scrollTop=messages.scrollHeight;setTimeout(()=>{wait.remove();add(answer(q))},420)};
launcher.addEventListener('click',()=>{chat.classList.add('open');chat.setAttribute('aria-hidden','false');launcher.style.display='none';if(!messages.children.length){if(history.length)history.forEach(m=>add(m.html,m.who,false));else welcome()}setTimeout(()=>input.focus(),100)});close.addEventListener('click',()=>{chat.classList.remove('open');chat.setAttribute('aria-hidden','true');launcher.style.display='flex'});form.addEventListener('submit',e=>{e.preventDefault();send(input.value)});chips.addEventListener('click',e=>{const b=e.target.closest('[data-question]');if(b)send(b.dataset.question)});
})();
</script>
