<script>document.documentElement.classList.add('nbx-js')</script>
@if($showPublicNav ?? false)
<script>document.documentElement.classList.add('nbx-global-public')</script>
<style>
    .nbx-global-public nav.nav{display:none!important}
    .nbx-public-nav{position:fixed;inset:0 0 auto;z-index:400;height:82px;border-bottom:1px solid rgba(141,166,201,.2);background:rgba(248,251,255,.9);backdrop-filter:blur(22px);font-family:Inter,system-ui,sans-serif;color:#0b2349}
    .nbx-public-nav *{box-sizing:border-box}.nbx-public-inner{width:min(1460px,calc(100% - 44px));height:100%;margin:auto;display:flex;align-items:center;gap:28px}.nbx-public-brand{display:flex;align-items:center;flex:0 0 auto}.nbx-public-brand img{display:block;width:auto;height:48px;max-width:245px;object-fit:contain}
    .nbx-public-links{display:flex;align-items:center;justify-content:center;gap:8px;margin-left:auto}.nbx-public-link,.nbx-products-trigger{display:flex;align-items:center;gap:7px;padding:10px 13px;border:0;border-radius:11px;background:transparent;color:#526784;text-decoration:none;font:750 13px Inter,system-ui;white-space:nowrap;transition:.18s}.nbx-public-link:hover,.nbx-products-trigger:hover,.nbx-public-link.active{background:#eaf1fb;color:#092e67}.nbx-products{position:relative}.nbx-products-trigger{cursor:pointer}.nbx-products-trigger svg{transition:.18s}.nbx-products:hover .nbx-products-trigger svg,.nbx-products:focus-within .nbx-products-trigger svg{transform:rotate(180deg)}
    .nbx-products-panel{position:absolute;top:calc(100% + 15px);left:50%;width:660px;padding:12px;display:grid;grid-template-columns:1fr 1fr;gap:10px;border:1px solid #d8e3f1;border-radius:22px;background:rgba(255,255,255,.98);box-shadow:0 25px 70px rgba(11,35,73,.18);opacity:0;visibility:hidden;transform:translate(-50%,8px);transition:.18s}.nbx-products:hover .nbx-products-panel,.nbx-products:focus-within .nbx-products-panel{opacity:1;visibility:visible;transform:translate(-50%,0)}
    .nbx-product-card{padding:17px;border:1px solid #e1e9f4;border-radius:16px;background:#f8fbff}.nbx-product-card:last-child{grid-column:1/-1}.nbx-product-card strong{display:block;color:#0a2a58;font-size:14px}.nbx-product-card p{margin:6px 0 13px;color:#647895;font-size:11px;line-height:1.55}.nbx-product-actions{display:flex;gap:8px}.nbx-product-actions a{padding:8px 11px;border-radius:9px;text-decoration:none;font-size:10px;font-weight:800}.nbx-product-actions a:first-child{color:#15509b;background:#e5effd}.nbx-product-actions a:last-child{color:#fff;background:#102f61}
    .nbx-public-cta{flex:0 0 auto;padding:12px 17px;border-radius:12px;color:#fff;text-decoration:none;font:800 12px Inter,system-ui;background:linear-gradient(135deg,#145dc8,#704eff);box-shadow:0 10px 28px rgba(31,92,195,.23)}.nbx-mobile-products{display:none}
    @media(max-width:900px){.nbx-public-nav{height:70px}.nbx-public-inner{width:min(100% - 24px,1460px);gap:10px}.nbx-public-brand img{height:39px;max-width:190px}.nbx-public-links{display:none}.nbx-public-cta{margin-left:auto;padding:10px 13px}.nbx-mobile-products{display:block;padding:10px 12px;border-radius:10px;color:#173c70;background:#e8f0fb;text-decoration:none;font-size:11px;font-weight:800}}
    @media(max-width:520px){.nbx-public-brand img{height:33px;max-width:150px}.nbx-public-cta{display:none}.nbx-mobile-products{margin-left:auto}}
</style>
<header class="nbx-public-nav" aria-label="Niyantron website navigation">
    <div class="nbx-public-inner">
        <a class="nbx-public-brand" href="/" aria-label="Niyantron home"><img src="{{ asset('brand/niyantron-logo-transparent.png') }}" alt="Niyantron"></a>
        <nav class="nbx-public-links" aria-label="Main navigation">
            <a class="nbx-public-link {{ request()->is('/') ? 'active' : '' }}" href="/">Home</a>
            <div class="nbx-products">
                <button class="nbx-products-trigger" type="button">Products <svg width="12" height="12" viewBox="0 0 20 20" fill="none" aria-hidden="true"><path d="m5 8 5 5 5-5" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg></button>
                <div class="nbx-products-panel">
                    <article class="nbx-product-card"><strong>OpsBridge</strong><p>IT assets, endpoints, people, software and lifecycle control.</p><div class="nbx-product-actions"><a href="{{ route('public.products.opsbridge') }}">Explore product</a><a href="https://opsbridge.niyantron.com/login">Sign in</a></div></article>
                    <article class="nbx-product-card"><strong>Niyantron ERP</strong><p>Procurement, dynamic QC, inventory, CRM, sales and finance.</p><div class="nbx-product-actions"><a href="{{ route('public.products.erp') }}">Explore product</a><a href="https://erp.niyantron.com/login">Sign in</a></div></article>
                    <article class="nbx-product-card"><strong>Niyantron Offers</strong><p>A secure buyer workspace for broadcasts, bids and negotiations.</p><div class="nbx-product-actions"><a href="https://bid.niyantron.com">Open buyer portal</a><a href="https://bid.niyantron.com/login">Buyer sign in</a></div></article>
                </div>
            </div>
            <a class="nbx-public-link {{ request()->is('about') ? 'active' : '' }}" href="/about">About</a>
            <a class="nbx-public-link {{ request()->is('contact') ? 'active' : '' }}" href="/contact">Contact</a>
        </nav>
        <a class="nbx-mobile-products" href="/#products">Products</a>
        <a class="nbx-public-cta" href="/contact">Talk to Niyantron</a>
    </div>
</header>
@endif
<style>.nbx-loader{display:none}.nbx-js .nbx-loader{position:fixed;z-index:9999;inset:0;display:grid;place-items:center;background:radial-gradient(circle at 50% 44%,#102e5d,#06101e 52%,#030914);transition:opacity .45s ease,visibility .45s ease}.nbx-loader.is-ready{opacity:0;visibility:hidden;pointer-events:none}.nbx-loader-inner{text-align:center;color:#fff}.nbx-symbol{position:relative;width:92px;height:92px;margin:auto;display:grid;place-items:center}.nbx-symbol:before,.nbx-symbol:after{content:"";position:absolute;inset:-12px;border:1px solid rgba(61,213,255,.36);border-radius:30px;transform:rotate(45deg);animation:nbx-orbit 2.2s linear infinite}.nbx-symbol:after{inset:-25px;border-color:rgba(117,87,255,.22);animation-direction:reverse;animation-duration:3.2s}.nbx-symbol img{position:relative;z-index:2;width:72px;height:72px;object-fit:contain;filter:drop-shadow(0 0 25px rgba(62,149,255,.42));animation:nbx-breathe 1.5s ease-in-out infinite}.nbx-loader strong{display:block;margin-top:27px;font:700 11px Inter,system-ui;letter-spacing:.2em}.nbx-loader small{display:block;margin-top:7px;color:#829ab9;font:500 9px Inter,system-ui;letter-spacing:.12em}@keyframes nbx-orbit{to{transform:rotate(405deg)}}@keyframes nbx-breathe{50%{transform:scale(.92);opacity:.76}}.nbx-cursor,.nbx-cursor-ring{display:none}@media(pointer:fine) and (prefers-reduced-motion:no-preference){.nbx-cursor,.nbx-cursor-ring{position:fixed;z-index:10000;left:0;top:0;display:block;pointer-events:none;border-radius:50%;opacity:0}.nbx-cursor{width:7px;height:7px;background:#36dbff;box-shadow:0 0 14px #36dbff}.nbx-cursor-ring{width:31px;height:31px;border:1px solid rgba(54,219,255,.55);transition:width .18s,height .18s,border-color .18s,background .18s}.nbx-cursor-ring.is-action{width:45px;height:45px;border-color:rgba(116,87,255,.72);background:rgba(116,87,255,.08)}body.nbx-cursor-active{cursor:none}body.nbx-cursor-active a,body.nbx-cursor-active button,body.nbx-cursor-active summary,body.nbx-cursor-active label{cursor:none}body.nbx-cursor-active input,body.nbx-cursor-active textarea,body.nbx-cursor-active select,body.nbx-cursor-active [contenteditable]{cursor:auto}}@media(prefers-reduced-motion:reduce){.nbx-symbol:before,.nbx-symbol:after,.nbx-symbol img{animation:none}}</style>
<div class="nbx-loader" id="nbxLoader" role="status" aria-label="Loading Niyantron"><div class="nbx-loader-inner"><div class="nbx-symbol"><img src="{{ asset('brand/niyantron-symbol-gradient.png') }}" alt=""></div><strong>NIYANTRON</strong><small>CONNECTED CONTROL</small></div></div><i class="nbx-cursor" id="nbxCursor"></i><i class="nbx-cursor-ring" id="nbxCursorRing"></i>
<script>(()=>{const loader=document.getElementById('nbxLoader'),dot=document.getElementById('nbxCursor'),ring=document.getElementById('nbxCursorRing'),ready=()=>loader?.classList.add('is-ready');if(document.readyState==='complete')setTimeout(ready,260);else addEventListener('load',()=>setTimeout(ready,260),{once:true});setTimeout(ready,3200);if(!matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches||!dot||!ring)return;document.body.classList.add('nbx-cursor-active');let x=innerWidth/2,y=innerHeight/2,rx=x,ry=y;addEventListener('mousemove',e=>{x=e.clientX;y=e.clientY;dot.style.opacity=ring.style.opacity='1';dot.style.transform=`translate3d(${x-3.5}px,${y-3.5}px,0)`},{passive:true});addEventListener('mouseout',e=>{if(!e.relatedTarget)dot.style.opacity=ring.style.opacity='0'});const loop=()=>{rx+=(x-rx)*.16;ry+=(y-ry)*.16;ring.style.transform=`translate3d(${rx-15.5}px,${ry-15.5}px,0)`;requestAnimationFrame(loop)};loop();document.addEventListener('mouseover',e=>ring.classList.toggle('is-action',!!e.target.closest('a,button,summary,label,[role="button"]')),{passive:true})})()</script>
