<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="@yield('description')">
    <meta name="theme-color" content="#07101e">
    <title>@yield('title') | Niyantron</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Sora:wght@600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        :root{--bg:#07101e;--panel:#0e1a2c;--panel2:#12233b;--text:#f4f8ff;--muted:#9db0cb;--line:rgba(255,255,255,.12);--blue:#2878ff;--cyan:#2ee4ff;--green:#2de39f;--violet:#7457ff;--gold:#ffc857}
        *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif;overflow-x:hidden}a{color:inherit}.container{width:min(1180px,calc(100% - 40px));margin:auto}
        .nav{position:fixed;inset:0 0 auto;z-index:50;background:rgba(255,255,255,.96);border-bottom:1px solid rgba(8,42,94,.1);box-shadow:0 10px 32px rgba(4,18,44,.08);backdrop-filter:blur(18px)}.nav-inner{height:82px;display:flex;align-items:center;justify-content:space-between;gap:28px}.brand img{display:block;height:52px;width:auto}.nav-links{display:flex;align-items:center;gap:28px;color:#526783;font-size:14px;font-weight:700}.nav-links a{text-decoration:none}.nav-links a:hover,.nav-links a.active{color:#082a5e}.nav-cta{background:linear-gradient(135deg,#4f8cff,#2868ff);border-radius:999px;color:#fff!important;padding:12px 18px;box-shadow:0 12px 25px rgba(40,120,255,.22)}
        .hero{min-height:100vh;position:relative;display:flex;align-items:center;padding:130px 0 80px;overflow:hidden}.hero-grid{display:grid;grid-template-columns:1.05fr .95fr;gap:72px;align-items:center;position:relative;z-index:3}.kicker{display:inline-flex;align-items:center;gap:8px;padding:8px 13px;border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.06);color:#dce9ff;font-size:12px;font-weight:800;letter-spacing:.08em;text-transform:uppercase}.kicker i{color:var(--cyan)}h1,h2,h3{margin:0;font-family:Sora,Inter,sans-serif}h1{font-size:clamp(48px,6.2vw,84px);line-height:1.02;letter-spacing:-.055em;margin-top:24px}.gradient-text{background:linear-gradient(90deg,var(--cyan),#4f8cff 50%,#8a68ff);-webkit-background-clip:text;color:transparent}.hero-copy p{max-width:680px;color:var(--muted);font-size:18px;line-height:1.75;margin:25px 0 0}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.btn{display:inline-flex;align-items:center;justify-content:center;gap:8px;border-radius:999px;padding:14px 20px;text-decoration:none;font-weight:800}.btn-primary{background:linear-gradient(135deg,var(--blue),#5e42ff);box-shadow:0 16px 35px rgba(40,120,255,.25)}.btn-secondary{border:1px solid rgba(255,255,255,.22);background:rgba(255,255,255,.06)}
        .scene{height:540px;position:relative;perspective:1200px}.scene-core{position:absolute;inset:90px 42px 60px;border:1px solid rgba(255,255,255,.16);border-radius:40px;background:linear-gradient(145deg,rgba(30,54,91,.78),rgba(8,18,34,.86));box-shadow:0 50px 100px rgba(0,0,0,.42),inset 0 1px rgba(255,255,255,.16);transform:rotateY(-9deg) rotateX(5deg);transition:transform .2s ease;overflow:hidden}.scene-core:before{content:"";position:absolute;width:240px;height:240px;border-radius:50%;background:var(--scene-glow,var(--blue));filter:blur(80px);opacity:.28;right:-40px;top:-40px}.command-head{padding:24px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.command-head small{color:var(--cyan);font-weight:800;letter-spacing:.12em}.command-body{padding:24px;display:grid;gap:14px}.signal{border:1px solid var(--line);border-radius:18px;background:rgba(255,255,255,.055);padding:18px}.signal-top{display:flex;justify-content:space-between;gap:12px;font-weight:800}.signal p{color:var(--muted);font-size:13px;line-height:1.55;margin:8px 0 0}.status{color:var(--green);font-size:11px}.orbit{position:absolute;border:1px solid rgba(79,140,255,.28);border-radius:50%;animation:orbit 14s linear infinite}.orbit.o1{width:420px;height:160px;left:15px;top:190px;transform:rotate(-16deg)}.orbit.o2{width:350px;height:350px;right:-70px;top:60px;animation-duration:19s}.node{position:absolute;width:18px;height:18px;border-radius:50%;background:var(--cyan);box-shadow:0 0 28px var(--cyan);animation:float 4s ease-in-out infinite}.n1{right:9%;top:18%}.n2{left:8%;bottom:20%;background:var(--violet);box-shadow:0 0 28px var(--violet);animation-delay:-1.5s}.n3{right:4%;bottom:10%;background:var(--green);box-shadow:0 0 28px var(--green);animation-delay:-2.3s}@keyframes orbit{to{transform:rotate(344deg)}}@keyframes float{50%{transform:translateY(-16px)}}
        .section{padding:100px 0;position:relative}.section.alt{background:#0a1424}.section-head{max-width:780px}.eyebrow{color:var(--cyan);font-size:12px;font-weight:850;letter-spacing:.16em;text-transform:uppercase}.section h2{font-size:clamp(36px,4.5vw,58px);line-height:1.08;letter-spacing:-.045em;margin-top:14px}.section-head>p{color:var(--muted);font-size:17px;line-height:1.7;margin:18px 0 0}.feature-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:42px}.feature{min-height:250px;border:1px solid var(--line);border-radius:24px;background:linear-gradient(160deg,rgba(22,36,61,.92),rgba(11,22,39,.96));padding:26px;position:relative;overflow:hidden;transition:.25s}.feature:hover{transform:translateY(-5px);border-color:rgba(79,140,255,.48);box-shadow:0 24px 55px rgba(0,0,0,.2)}.feature .icon{width:46px;height:46px;display:grid;place-items:center;border-radius:15px;background:rgba(79,140,255,.14);color:var(--cyan);font-size:21px}.feature h3{font-size:19px;margin-top:25px}.feature p{color:var(--muted);font-size:14px;line-height:1.65;margin:12px 0 0}.feature .number{position:absolute;right:18px;top:12px;color:rgba(255,255,255,.045);font:700 64px/1 Sora}
        .flow{display:grid;grid-template-columns:repeat(4,1fr);gap:0;margin-top:48px;border:1px solid var(--line);border-radius:28px;overflow:hidden}.flow-step{padding:28px;background:rgba(255,255,255,.035);border-right:1px solid var(--line)}.flow-step:last-child{border:0}.flow-step span{display:grid;place-items:center;width:34px;height:34px;border-radius:11px;background:rgba(79,140,255,.16);color:var(--cyan);font-weight:800}.flow-step h3{font-size:16px;margin-top:18px}.flow-step p{color:var(--muted);font-size:13px;line-height:1.55}.outcomes{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:45px}.outcome{border-radius:28px;padding:34px;border:1px solid var(--line);background:linear-gradient(135deg,rgba(40,120,255,.14),rgba(116,87,255,.08))}.outcome strong{font:700 38px/1 Sora}.outcome p{color:var(--muted);line-height:1.6}.cta{margin:40px auto 100px;padding:46px;border:1px solid var(--line);border-radius:32px;background:radial-gradient(circle at 80% 20%,rgba(46,228,255,.2),transparent 34%),linear-gradient(135deg,#13284a,#0a1424);display:flex;justify-content:space-between;align-items:center;gap:32px}.cta h2{font-size:38px}.cta p{color:var(--muted)}footer{border-top:1px solid var(--line);padding:30px 0;color:var(--muted);font-size:13px}.footer-row{display:flex;align-items:center;justify-content:space-between;gap:20px}.footer-row img{filter:brightness(0) invert(1);opacity:.76;height:26px;width:auto}
        @media(max-width:900px){.nav-links{display:none}.hero-grid{grid-template-columns:1fr;gap:24px}.hero{padding-top:120px}.scene{height:470px}.feature-grid{grid-template-columns:1fr 1fr}.flow{grid-template-columns:1fr 1fr}.flow-step:nth-child(2){border-right:0}.flow-step{border-bottom:1px solid var(--line)}.outcomes{grid-template-columns:1fr}.cta{align-items:flex-start;flex-direction:column}}
        @media(max-width:620px){.container{width:min(100% - 28px,1180px)}.nav-inner{height:72px}.brand img{height:40px}.nav-cta{padding:10px 13px;font-size:12px}h1{font-size:43px}.hero{padding-bottom:40px}.scene{height:410px}.scene-core{inset:54px 8px 40px}.feature-grid,.flow{grid-template-columns:1fr}.flow-step{border-right:0}.cta{margin-bottom:60px;padding:28px}.cta h2{font-size:30px}}
        @media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.orbit,.node{animation:none}.feature{transition:none}}
    </style>
    @stack('styles')
</head>
<body style="--scene-glow:@yield('scene-glow','#2878ff')">
<nav class="nav"><div class="container nav-inner">
    <a class="brand" href="/"><img src="{{ asset('brand/niyantron-logo-full.jpg') }}" alt="Niyantron" width="239" height="52"></a>
    <div class="nav-links"><a href="/">Home</a><a href="{{ route('public.products.opsbridge') }}" class="{{ request()->routeIs('public.products.opsbridge')?'active':'' }}">OpsBridge product</a><a href="{{ route('public.products.erp') }}" class="{{ request()->routeIs('public.products.erp')?'active':'' }}">ERP product</a><a href="/about">About</a><a href="/contact">Contact</a></div>
    <a class="nav-cta" href="@yield('login-url')">@yield('login-label','Sign in to product')</a>
</div></nav>
@yield('content')
<footer><div class="container footer-row"><img src="{{ asset('brand/niyantron-logo-transparent.png') }}" alt="Niyantron"><span>Connected control for modern organizations.</span><span>&copy; {{ date('Y') }} Niyantron</span></div></footer>
<script>
    const scene=document.querySelector('.scene-core');
    if(scene&&!matchMedia('(prefers-reduced-motion: reduce)').matches){
        document.addEventListener('pointermove',e=>{const x=(e.clientX/innerWidth-.5)*7;const y=(e.clientY/innerHeight-.5)*-5;scene.style.transform=`rotateY(${-9+x}deg) rotateX(${5+y}deg)`});
    }
</script>
</body></html>
